import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DEVJYOT
 */
public class userdata extends javax.swing.JFrame {
    String usernameGlobal;
    /**
     * Creates new form user data
     */
    public userdata() {
        initComponents();
    }
    public userdata(String username)
    {
     initComponents();
     usernameGlobal=username;
     events_btn.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sushi_lab = new javax.swing.JLabel();
        events_btn = new javax.swing.JButton();
        communities_tab = new javax.swing.JButton();
        personalInformation_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_tab = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sushi_lab.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        sushi_lab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sushi_lab.setText("Sushi");

        events_btn.setText("View my recent activity in events");
        events_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                events_btnActionPerformed(evt);
            }
        });

        communities_tab.setText("Communities I follow");
        communities_tab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communities_tabActionPerformed(evt);
            }
        });

        personalInformation_btn.setText("Personal Information");

        data_tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(data_tab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(sushi_lab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(events_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(communities_tab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(personalInformation_btn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sushi_lab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(events_btn)
                    .addComponent(communities_tab)
                    .addComponent(personalInformation_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void events_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_events_btnActionPerformed
//Will show all the recent activities of the user in any events
data_tab.getColumnModel().getColumn(0).setHeaderValue("Events");
try
{
 DefaultTableModel m=(DefaultTableModel)data_tab.getModel();
 Class.forName("java.sql.DriverManager");
 Connection con;
 con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sushi","root","amity");
 Statement stmt=(Statement)con.createStatement();
 String query="selct association from "+usernameGlobal+" where association like '%event%'";
 ResultSet rs=stmt.executeQuery(query);
 while(rs.next())
 {
  String eventRelation=rs.getString("association");
  m.addRow(new Object[]{eventRelation});
 }
}
catch(Exception e)
{
 JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_events_btnActionPerformed

    private void communities_tabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communities_tabActionPerformed
//Will show the user of all the communities he/she follows
data_tab.getColumnModel().getColumn(0).setHeaderValue("Communities");
try
{
 DefaultTableModel m=(DefaultTableModel)data_tab.getModel();
 Class.forName("java.sql.DriverManager");
 Connection con;
 con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sushi","root","amity");
 Statement stmt=(Statement)con.createStatement();
 String query="selct association from "+usernameGlobal+" where association like '%community%'";
 ResultSet rs=stmt.executeQuery(query);
 while(rs.next())
 {
  String community=rs.getString("association");
  m.addRow(new Object[]{community});
 }
}
catch(Exception e)
{
 JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_communities_tabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userdata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton communities_tab;
    private javax.swing.JTable data_tab;
    private javax.swing.JButton events_btn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton personalInformation_btn;
    private javax.swing.JLabel sushi_lab;
    // End of variables declaration//GEN-END:variables
}
